#Parameters for Admittance Controller in assisted mode
final_vel_topic: /cmd_vel
human_wrench_topic: /agora_sw/frc
update_params_service: /update_parameters
control_parameters:
  rate: 50
  mode: user
  mass: 20
  ldaming: 10
  inertia: 20
  adamping: 10
angular_vel_limit: 1.0
linear_vel_limit: 1.5
